---
- name: Sample
  hosts: localhost
  connection: local
  tasks:
    - name: Hello
      ansible.builtin.command: echo "Hello, Ansible!"
      register: hello_result
      changed_when: false

    - name: Show result
      ansible.builtin.debug:
        var: hello_result.stdout
