version: 3

images:
  base_image:
    name: quay.io/ansible/ansible-runner:latest

dependencies:
  galaxy: requirements.yml
  python: requirements.txt
  system:
    - git-core
    - libxml2-dev
    - libxslt1-dev

options:
  package_manager_path: /usr/bin/dnf

additional_build_steps:
  prepend_base:
    - RUN pip3 install --upgrade pip
  append_final:
    - RUN ansible-galaxy collection install arista.avd
    - RUN echo "Arista AVD Execution Environment Ready"
